export const btnConfig = [
  { content: "C", className: "col-span-3 bg-amber-300" },
  { content: "/", className: "bg-amber-300" },
  { content: 7 },
  { content: 8 },
  { content: 9 },
  { content: "x", className: "bg-amber-300" },
  { content: 4 },
  { content: 5 },
  { content: 6 },
  { content: "-", className: "bg-amber-300" },
  { content: 1 },
  { content: 2 },
  { content: 3 },
  { content: "+", className: "bg-amber-300" },
  { content: 0, className: "col-span-2" },
  { content: "." },
  { content: "=", className: "bg-amber-300" },
];
